# Generated by Django 4.1.4 on 2023-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=25)),
            ],
        ),
    ]
